### ISSUE TITLE
Why don't you make a Nano Defender version for uBlock Origin?

### ISSUE THREAD

**Issue by davidhedlund** [NanoAdblocker/NanoDefender#11]
I think it would be really useful to make a stand alone version of Nano Defender for uBlock Origin. What do you think?

**Comment by davidhedlund** [comment]
https://github.com/NanoAdblocker/NanoCore/issues/93

**Comment by jspenguin2017** [comment]
Nano Defender works with uBO, I don't want to have more stuff to maintain.

**Comment by davidhedlund** [comment]
> Nano Defender works with uBO

This should be mentioned at https://addons.mozilla.org/en-US/firefox/addon/real-nano-defender/

**Comment by jspenguin2017** [comment]
Is there any benefit to me for doing that?

**Comment by davidhedlund** [comment]
Yes, uBO users will use Nano Defender.

**Comment by jspenguin2017** [comment]
Gorhill publicly said uBO does not need Nano Defender, I'll probably just cause more confusion and complains if I say that in the description. 
The Chrome version is different due to legacy reasons. I'll eventually remove that phrase as well. I probably won't drop the support though.

**Comment by davidhedlund** [comment]
You are not working with Raymond (Gorhill) so I think you should state your opinions in your own projects. I think Nano Defender should be part of uBO.

**Comment by jspenguin2017** [comment]
He is a smart guy, but is impossible to work with. He sees performance as the number 1 priority, and Nano Defender injects JavaScript to every page, which is dumping performance down the toilet in his book.

**Comment by davidhedlund** [comment]
Nano Defender could be disabled by default in uBO.

**Comment by davidhedlund** [comment]
How useful wouldn't it be to have a "Enable anti-adblocking (slower performance)" checkbox in uBO?

**Comment by jspenguin2017** [comment]
That's the problem, it *cannot* be a toggle. It is either hard coded into the extension or you'll have race condition. If it misbehave, you'll have to disable the entire extension.

**Comment by davidhedlund** [comment]
> it cannot be a toggle. It is either hard coded into the extension or you'll have race condition. If it misbehave, you'll have to disable the entire extension.

Can you mention this in [README.MD](https://github.com/NanoAdblocker/NanoDefender/blob/master/README.MD)?

**Comment by jspenguin2017** [comment]
You are the first person to ask this question, if more people ask the same question, I'll add it to a FAQ or to README.
