### ISSUE TITLE
uBO Safari port is being submitted to extension gallery. Any plans for support? 

### ISSUE THREAD

**Issue by nidstigator** [NanoAdblocker/NanoDefender#12]
Hi there 

I was just wondering if you were planning on supporting Safari at all? 

The Safari port of uBO is now updated to latest version of uBO and is working well. I’ve been running it for a while now. 

https://github.com/el1t/uBlock-Safari

Thanks for your amazing work!

**Comment by jspenguin2017** [comment]
First, making Safari version will cost $99 per year, and I'm definitely not going to pay for that. Also, I don't have any Apple product, and developing Safari version require macOS. So the port needs to come from another contributor.

**Comment by nidstigator** [comment]
Got you. Valid points. Was just curious if it's ever going to be supported. Thanks for responding!

**Comment by jspenguin2017** [comment]
I can answer questions if someone wants to start a port, same thing for Nano Adblocker. 
I do support Edge though. Although the Edge version being stuck in review is out of my control.

**Comment by nidstigator** [comment]
FYI, I just came across this: 

https://developer.apple.com/news/?id=01032018a

Apple is now wavering fees in some cases.

I know you said you don't have any Apple HW, but was just bringing your attention to this in case you change your mind in the future. 

All the best.

**Comment by jspenguin2017** [comment]
Hum, we might be eligible for "nonprofit organizations", but not sure. 
Apple's hardware are too expensive, and I can't afford that, that's unlikely to change in the near future unless someone sponsors me.

**Comment by jspenguin2017** [comment]
I won't install macOS as the primary OS, that's out of question, it must be a VM.

**Comment by nidstigator** [comment]
Also possible:

https://rektstack.com/macos-high-sierra-in-vmware-workstation-12/

**Comment by jspenguin2017** [comment]
I can't patch VMWare, I need it for another VM.

**Comment by jspenguin2017** [comment]
> Once you receive an enrollment ID, you can submit a fee waiver, which will also require your EIN/tax ID

Well, looks like it needs to be a real registered organization in the United States, I guess that's not happening neither. 

Looks like someone else got to do the port.
