### ISSUE TITLE
Remove https://nanoadblocker.github.io/NanoDefender/

### ISSUE THREAD

**Issue by davidhedlund** [NanoAdblocker/NanoDefender#13]
https://jspenguin2017.github.io/uBlockProtector/ is used to display these messages:
> Your adblocker is not enabled!
> Nano Defender is not enabled!

* The old page https://nanoadblocker.github.io/NanoDefender/ do not display the messages above.
* Shouldn't https://nanoadblocker.github.io/NanoDefender/ be changed to https://jspenguin2017.github.io/uBlockProtector/ at https://addons.mozilla.org/en-US/firefox/addon/real-nano-defender/ and possibly other sources?

**Comment by jspenguin2017** [comment]
Working as intended.

**Comment by davidhedlund** [comment]
> Working as intended.

What do you mean? I cannot figure out if they are disabled by follow the link listed at https://addons.mozilla.org/en-US/firefox/addon/real-nano-defender/

**Comment by jspenguin2017** [comment]
I don't want to show warnings if you came from AMO.

**Comment by davidhedlund** [comment]
Then I think there should be a dedicated test page to view if Nano Adblocker and Nano Defender are disabled. The link can be added to both:
* https://jspenguin2017.github.io/uBlockProtector/
* https://nanoadblocker.github.io/NanoDefender/

**Comment by jspenguin2017** [comment]
The installation was a problem in the past, as Nano Defender has 2 parts. It's no longer the case, as Nano Adblocker will auto-config the second part. 
For uBO, there are now too many steps and I'm not going to test all that.

**Comment by davidhedlund** [comment]
I agree that the installation procedure should be shorter. Thank you for dealing with it.

**Comment by jspenguin2017** [comment]
It was 2 steps and now it's 1. 
I'm not going to make compromise for the sake of uBO, so installation steps for uBO will be as long as it takes.

**Comment by davidhedlund** [comment]
We all want this. Namaste.
