### ISSUE TITLE
Wrong GitHub link at AMO

### ISSUE THREAD

**Issue by davidhedlund** [NanoAdblocker/NanoDefender#14]
The link on [AMO](https://addons.mozilla.org/en-US/firefox/addon/real-nano-defender/) is wrong:
> BETA SOFTWARE, REPORT BUG HERE: https://github.com/NanoAdblocker/NanoFilters/issues

This made me report an [issue](https://github.com/NanoAdblocker/NanoFilters/issues/19) to the wrong repository, and more people will do it if you don't change it to:
> BETA SOFTWARE, REPORT BUG HERE: https://github.com/NanoAdblocker/NanoDefender/issues/

Then you might want to add this to [Nano Adblocker](https://addons.mozilla.org/en-US/firefox/addon/real-nano-adblocker/):
> Report filters issues here: https://addons.mozilla.org/en-US/firefox/addon/real-nano-adblocker/

**Comment by jspenguin2017** [comment]
Intended.

**Comment by jspenguin2017** [comment]
I will add a button to Nano Adblocker's popup page for reporting filter issues.

**Comment by davidhedlund** [comment]
Thanks.
