### ISSUE TITLE
Firefox ESR

### ISSUE THREAD

**Issue by joksik** [NanoAdblocker/NanoDefender#15]
Hi, i use Firefox ESR in work and the latest version this firefox is 52.0.6 so i can`t install NanoDefender which requires Firefox 56 but i cant install Nano Adblocker on my firefox esr so I was wondering can you lower the requirements for NanoDefender?

**Comment by jspenguin2017** [comment]
I need new APIs of Firefox 57, I won't support older versions unless I get a proper platform shim working.

**Comment by hawkeye116477** [comment]
@joksik You can probably install it by unofficial way. This works in Waterfox 56, maybe this will work also on Firefox ESR.
Just install -> https://addons.mozilla.org/pl/firefox/addon/checkcompatibility/. Then go here -> https://addons.mozilla.org/en-US/firefox/addon/real-nano-defender/versions/ and click `Download Anyway`. Then move xpi file to address bar and confirm to install it. But of course probably not all functions will be working and probably won't be any updates and you will must install it by manual.

**Comment by jspenguin2017** [comment]
I probably will not support older Firefox, even though it should work most of the time. Defusing anti-adblock scripts is an arm race, and you got to stay on top of things to be ahead of the race. Outdated browsers just gets in the way.
