### ISSUE TITLE
not work on italiashare.net

### ISSUE THREAD

**Issue by gabri25ele** [NanoAdblocker/NanoDefender#17]
on italiashare.net defender not work anymore :(
any idea to fix it?

**Comment by jspenguin2017** [comment]
Ops, I totally forgot to fix it... 
Duplicate of https://github.com/jspenguin2017/uBlockProtector/issues/126

**Comment by jspenguin2017** [comment]
Duplicate of https://github.com/jspenguin2017/uBlockProtector/issues/126
