### ISSUE TITLE
NSFW! avgle.com

### ISSUE THREAD

**Issue by zaphodbeebblebrox** [NanoAdblocker/NanoDefender#19]
### The video does not play and the site redirects to url?adblock_detected after a short period of time

1. Go to video
2. Wait 15 to 30 seconds

### Environment (Required): 

- Windows 10
- Chrome 63.0.3239.132 64-bit
- Nano Adblocker 1.0.0.28 , Nano Defender 13.28

#### Your filter lists (Required): 
Enabled:
Nano Defender Integration
Nano Filters
Nano Filters-Annoyance

No custom filters.

**Comment by jspenguin2017** [comment]
Duplicate of https://github.com/jspenguin2017/uBlockProtector/issues/817
