### ISSUE TITLE
Cannot turn off/on NanoDefender from the add-on bar

### ISSUE THREAD

**Issue by davidhedlund** [NanoAdblocker/NanoDefender#22]
Sometime I need to temporarily need to turn off NanoDefender as quick as possible. Can you make NanoDefender turn on/off when I click it in the addon-bar instead of open the Add-on Manager entry for it ?

**Comment by jspenguin2017** [comment]
That's not implementable reasonably due to API restriction.

**Comment by davidhedlund** [comment]
You can do this with https://addons.mozilla.org/en-US/firefox/addon/nominer-block-coin-miners/

Why should this not be possible to do with NanoDefender?

**Comment by jspenguin2017** [comment]
Because Nano Defender isn't a miner blocker. Nano Adblocker blocks miners and it's configurable just like that extension.

**Comment by davidhedlund** [comment]
It's possible to turn of Nano Adblocker from the add-on bar when you click on it.

**Comment by jspenguin2017** [comment]
You can use an extension manager to achieve what you want.

**Comment by jspenguin2017** [comment]
That's correct, and Nano Defender is different. 
You can use an extension manager to achieve what you want.

**Comment by davidhedlund** [comment]
Ok, thank you for explaining this to me. Do you plan to implement my suggestion to Nano Defender if Firefox change the API restriction to make this possible?

**Comment by jspenguin2017** [comment]
With Firefox 57, it's possible to implement it, but it's not possible in Chrome. 
I will not implement it unless it works in Chrome as well. Pull request will be accepted once Nano Build is fully implemented.

**Comment by davidhedlund** [comment]
Ok, good to know.
