### ISSUE TITLE
lightnovelstranslations.com

### ISSUE THREAD

**Issue by japzone1** [NanoAdblocker/NanoDefender#24]
### Test link (required): 
https://lightnovelstranslations.com/

### Screenshot of the web page (including address bar and extension icons) (required): 
https://i.imgur.com/gpf0M1o.png

### Screenshot of the console (press `F12` to bring up the console) (required): 
https://i.imgur.com/tcd64IH.png

### Explain what was not right (optional if obvious): 
Site doesn't load at all if uBlock is enabled.

### Environment (Required): 

- Operating System and Version: Windows 10 x64 v1703
- Browser and Version: Firefox v59.0b7 (64-bit)
- Adblocker and Version:  uBlock Origin 1.15.4

#### Your filter lists (Required): 
https://screenshotscdn.firefoxusercontent.com/images/4c1393db-44f4-42f3-abe2-a46322c0f3db.png

**Comment by jspenguin2017** [comment]
Hum, it's from this plugin: `https://wordpress.org/plugins/detect-adblock/`
I'll make a generic rule.

**Comment by jspenguin2017** [comment]
@okiehsch Do you want to take the generic rule?

**Comment by jspenguin2017** [comment]
@okiehsch Can we have your input?

**Comment by okiehsch** [comment]
I asked gorhill, if he agrees I will add
`@@/wp-content/plugins/detect-adblock/js/ads.js$script,first-party`
`

**Comment by okiehsch** [comment]
And I did notice this thread, there is no need to ping me if I don't answer immediately.

**Comment by jspenguin2017** [comment]
Sorry, I thought you missed it as it was a day ago. 

As a side note, the generic rule will cover `tejikarao.kodaisi.net##script:inject(set-constant.js, AlobaidiDetectAdBlock, true)`.

**Comment by jspenguin2017** [comment]
Also there are some missed ads in `https://wp-time.com/best-detect-adblock-plugin-wordpress/`. 
```
wp-time.com##a[href^="https://goo.gl/"]:has(img)
wp-time.com###pop-ad-wrap
```
seems to work.

**Comment by okiehsch** [comment]
Fix added.

**Comment by jspenguin2017** [comment]
Also a few more: 
```
# https://github.com/jspenguin2017/uBlockProtector/issues/756
# Another WordPress plugin
/wp-content/plugins/end-of-adblock-cycle/*

# https://github.com/NanoAdblocker/NanoDefender/issues/25
# Could need a different fix for uBO
coolgames.com###mainContainerVideo:has(#adContainerVideo)

# https://github.com/jspenguin2017/uBlockProtector/issues/835
# The "found your file" overlay is fake
link.tl##.mobsplOverlay
link.tl##.mobsplBox

# https://github.com/jspenguin2017/uBlockProtector/issues/851
# Kind of annoyance, but it's pretty big
journaldugeek.com##.banner__content
```

**Comment by jspenguin2017** [comment]
Also one that could be a bit more difficult: 
```
# https://github.com/jspenguin2017/uBlockProtector/issues/752
wolframclient.net##script:inject(nano-remove-element-onready.js, [data-ad-client^="ca-pub-"])
```

**Comment by okiehsch** [comment]
`wolframclient.net` uses rocketscript, so
`||ajax.cloudflare.com/cdn-cgi/*/rocket.min.js$script,important,domain=wolframclient.net`
will "fix" any issue with that site, the question is does it break important site functionality.

**Comment by okiehsch** [comment]
About the annoyances, `uBlock-annoyance` is meant for annoyances that can't be easily fixed by the conventional annoyance-lists, i.e. filters with extended syntax.

**Comment by okiehsch** [comment]
`coolgames.com` is broken on my end, the game never starts even if I disable uBlock.

**Comment by okiehsch** [comment]
Your `/wp-content/plugins/end-of-adblock-cycle/*` fix won't work, they commented it out.

**Comment by okiehsch** [comment]
Fixed https://github.com/jspenguin2017/uBlockProtector/issues/756 with https://github.com/uBlockOrigin/uAssets/commit/45a392a8b0b36e12872ba66e3412053c10fc3ec6

**Comment by jspenguin2017** [comment]
Cool. Thanks for your time.

**Comment by jspenguin2017** [comment]
`coolgames.com` requires Flash btw.

**Comment by okiehsch** [comment]
Well, I would like your opinion regarding the `wolframclient.net` issue, if you have the time, do you see any breakage, or do you think adding 
`||ajax.cloudflare.com/cdn-cgi/*/rocket.min.js$script,important,domain=wolframclient.net`
could be added, if so I will add it to `uBlock-filters`.

**Comment by okiehsch** [comment]
`coolgames.net` I get the "the game will continue after these messages", then I get a loading screen, which turns black and then ...... nothing.
With or without flash enabled and uBlock disabled.

**Comment by jspenguin2017** [comment]
`wolframclient.net`

I'm not sure, the main script is quite long... Although I don't see immediate breakage. I'm planning on adding `:remove()` style filter for Chrome and honestly I don't like that script snippet. 

---

`coolgames.net` 

Yea, it doesn't use Flash, bad memory. The fix is currently in Nano Defender, with a surrogate for IMA SDK. The surrogate is in ES 6+ and use lots of inheritance, really hard to port. 

---

Also, before I forget, the price chart is broken on `https://www.coindesk.com/price/`. 
Rule: `@@/cdn-cgi/pe/bag2?*optimizely.com$domain=coindesk.com`
![image](https://user-images.githubusercontent.com/7283682/36128450-a89966ac-101f-11e8-845e-846001a88ded.png)

**Comment by okiehsch** [comment]
Fixed `coindesk.com`

**Comment by okiehsch** [comment]
Regarding `wolframclient.net`, how about
````
wolframclient.net##script:inject(setTimeout-defuser.js, detected, 0)
````

**Comment by jspenguin2017** [comment]
Huh, I'm surprised that that works. I thought the detection code is: 
```js
$(function() {
    var ad = $('[data-ad-client="ca-pub-5218363098774955"]');
    if (!ad.length)
        return;
    if (ad.css('display') === 'none') {
        $('.post-content').html("You must disable AdBlock to view this content.");
    }
});
```

Well, if it works it works I guess...

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/commit/01a7ec7190801aa6e397747719443e329d8db11a
