### ISSUE TITLE
coolgames.com

### ISSUE THREAD

**Issue by nitrocode** [NanoAdblocker/NanoDefender#25]
Is this an issue for uBO/uAssets or here? Apologies ahead of time.

Original post: https://github.com/reek/anti-adblock-killer/issues/3902

### Test link (required): 

http://www.coolgames.com/en/bubble-academy.html

### Screenshot of the web page (including address bar and extension icons) (required): 

![coolgames](https://i.imgur.com/T9wpwQH.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 

![coolgames2](https://i.imgur.com/TEBENsx.png)

### Explain what was not right (optional if obvious): 

trivial

### Reproduction steps (optional if trivial): 

trivial

### Environment (Required): 

- Operating System and Version: Ubuntu Xenial (16.04)
- Browser and Version: (Chrome 68)
- Adblocker and Version: (uBO 1.15.2)

#### Your filter lists (Required): 
```
uBlock filters
uBlock filters - Badware risks
uBlock filters - Privacy
uBlock filters - Resource Abuse
uBlock filters - Unbreak
EasyList
EasyPrivacy
Malware Domain List
Malware domains
Peter Lowe's Ad and tracking server list

```

#### Your custom filters (Required if you have any): 

See above

### Add everything else that you believe to be useful below (optional): 

Please see original issue https://github.com/reek/anti-adblock-killer/issues/3902

**Comment by nitrocode** [comment]
@jspenguin2017 I'm still getting the adblock message. Do I need to update something in NodeDefender or Chrome?

**Comment by jspenguin2017** [comment]
Make sure to properly install integration for uBO: https://jspenguin2017.github.io/uBlockProtector/

**Comment by nitrocode** [comment]
Oh ok. I mistakenly said I was still using uBO above but I switched over to NodeDefender and uninstalled uBO. I guess I will reinstall alongside NodeDefender and retry the site. Thank you.

**Comment by jspenguin2017** [comment]
Nano Defender isn't an adblocker, Nano Adblocker is.

**Comment by nitrocode** [comment]
Oh right. I feel foolish. Okay so I now have NanoDefender and NanoAdblocker installed. I'm still seeing the adblock wall on coolgames.

Sorry for having so much trouble. I'm not sure if it's my setup or if it's something else.

**Comment by jspenguin2017** [comment]
Really? Can you restart your browser and wait 15 seconds? It can be the cross extension messaging didn't land.

**Comment by nitrocode** [comment]
Ok so I ran a `chrome://restart` and I saw the same results in my loaded profile.

So I decided to create a new profile and only install the 2 addons NanoDefender and NanoAdblocker and I see the same results. Here is a new screen shot of my console output.

![coolgames-console](https://i.imgur.com/CuApJfQ.png)

**Comment by jspenguin2017** [comment]
That's weird, can you update filters and make sure `Nano Defender Integration` is enabled? 
![image](https://user-images.githubusercontent.com/7283682/36081481-906fb306-0f5c-11e8-9688-a7bf064ce960.png)

**Comment by nitrocode** [comment]
Ah wonderful. The `Node Defender Integration` was enabled but it did not auto update. Clicking `Update Now` and refreshing the page did the trick. 

Thank you so much!
