### ISSUE TITLE
lastnighton.com

### ISSUE THREAD

**Issue by nitrocode** [NanoAdblocker/NanoDefender#26]
### Test link (required): 

https://lastnighton.com/2018/02/23/real-time-bill-maher-tonight-february-23/

### Screenshot of the web page (including address bar and extension icons) (required): 

![img](https://i.imgur.com/JDNJwzX.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 

See above

### Environment (Required): 

- Operating System and Version: Ubuntu
- Browser and Version: Chrome 64
- Adblocker and Version: NanoAdblocker latest

#### Your filter lists (Required): 
Default

#### Your custom filters (Required if you have any): 
None

### Add everything else that you believe to be useful below (optional): 

It tries to hit https://api.segment.io/v1/t and it's blocked. This endpoint returns

    $ curl https://api.segment.io/v1/t
    {
      "success": true
    }

**Comment by jspenguin2017** [comment]
@okiehsch

**Comment by okiehsch** [comment]
Added to the "Admiral" list. https://github.com/uBlockOrigin/uAssets/commit/a43b5b5a61943e73d23237e24e8128e16c88d08c

**Comment by nitrocode** [comment]
Updated and confirmed fix. Thank you!
