### ISSUE TITLE
spiegel.de

### ISSUE THREAD

**Issue by taotsetung** [NanoAdblocker/NanoDefender#28]
### URLs where this issue occurs (Required)
http://www.spiegel.de/

### Screenshots (Required)
![image](https://user-images.githubusercontent.com/1525711/36855921-097097ea-1d75-11e8-92db-6d475b4c2408.png)

### Screenshot of console (Required, press `F12` to open the console)
![image](https://user-images.githubusercontent.com/1525711/36855962-2031e934-1d75-11e8-99dc-b688feaaccc4.png)

#### Environment (Required)

- Operating System and Version: Windows 10 Enterprise Version 1709
- Browser and Version: Google Chrome Version 64.0.3282.186
- Nano Adblocker Version: 1.0.0.33
- Nano Defender Version: 13.38

#### Your filter lists (Required)
All Default

**Comment by jspenguin2017** [comment]
Fixed here: https://github.com/uBlockOrigin/uAssets/issues/1641
