### ISSUE TITLE
Conflict with HTTPS Everywhere 2018.2.26

### ISSUE THREAD

**Issue by upekshapriya** [NanoAdblocker/NanoDefender#29]
I'm getting a message in Chrome that tells me there's an extension problem and sometimes pages don't load at all as a result (it seems).

The following warning appears in the HTTPS Everywhere 2018.2.26 extension 

Warning:
This extension failed to redirect a network request to https://www.google-analytics.com/ga.js because another extension (Nano Adblocker) redirected it to chrome-extension://gabbbocakeomblphkmmnoamkioajlkfo/web_accessible_resources/c2c7eb5240aa19439b7ebbf38d6789e5.javascript?secret=io0lt3pkgdyo.

#### Environment (Required)

- Operating System and Version:  MacOS 10.13.3
- Browser and Version: Chrome 64.0.3282.186
- Nano Adblocker Version:  1.0.0.34
- Nano Defender Version: 13.41

#### Your filter lists (Required)

Nano Defender Integration​​​​​2,719 used out of 2,757​​​​
Nano filters​​​​​55 used out of 57​​​​
Nano filters – Annoyance​​​​​11 used out of 11​​​​
Nano filters – Timer bypassing (sometimes works)​​​​​0 used out of 0​​​​
Nano filters – Whitelist​​​​​0 used out of 0​​​​
uBlock filters​​​​​4,343 used out of 4,343​​​​
uBlock filters – Annoyances​​​​​52 used out of 52​​​​
uBlock filters – Badware risks​​​​​8 used out of 8​​​​
uBlock filters – Privacy​​​​​65 used out of 65​​​​
uBlock filters – Resource abuse​​​​​211 used out of 213​​​​
uBlock filters – Unbreak​​​​​311 used out of 311​​​​
Adblock Warning Removal List​​​​​389 used out of 405​​​​
EasyList​​​​​80,463 used out of 80,756​​​​
EasyPrivacy​​​​​14,362 used out of 14,487​​​​
Malware Domain List​​​​​1,130 used out of 1,146​​​​
Malware domains​​​​​18,563 used out of 18,563​​​​

#### Your custom filters (Required if you have any)

! 01/03/2018, 16:09:46 https://www.itv.com/
||toots-a.akamaihd.net/priority/pushdown/118NovSR-NEWURL_20171129101801/5a05955414c263_86007051_0.jpg$image

**Comment by jspenguin2017** [comment]
There's nothing I can do about this.

**Comment by upekshapriya** [comment]
Is there anything I can do though to stop this happening?

**Comment by jspenguin2017** [comment]
Well, with Chromium I think you can suppress the error, or uninstall one of the extensions.

**Comment by User486375** [comment]
Couldn't you do something similar to what Decentraleyes did [here](https://decentraleyes.org/configure-https-everywhere/) and [here](https://github.com/Synzvato/decentraleyes/wiki/Frequently-Asked-Questions#why-am-i-receiving-https-everywhere-related-warnings-on-chrome-or-chromium)?

**Comment by jspenguin2017** [comment]
@User486375 No, I will not whitelist a tracking script for everyone just so HTTPS Everywhere can redirect it to HTTPS, that makes absolutely no sense.

**Comment by User486375** [comment]
What I meant is how Decentraleyes has a list of rules you untick to make it compatible with HTTPS Everywhere. I suppose this would be something people would have to submit as issues to be added to a list of conflicting sites and maybe something you don't want to have to deal with.

**Comment by jspenguin2017** [comment]
I don't have time to maintain such list, it's up to the user to write the rules. Or if someone wants to make a filter list for it that would work too.

**Comment by gametimebrizzle** [comment]
@User486375 Just let it go buddy, he's not fixing it.  He's made that pretty clear.  There really isn't anything to fix on his end anyways, go bug EFF lol - they have more resources. Or try to come up with a solution/workaround (and share it with everyone) if you really want it dealt with.

**Comment by jspenguin2017** [comment]
I'm not going to fix extension conflicts, period.
