### ISSUE TITLE
ouo.io, ouo.press

### ISSUE THREAD

**Issue by version365** [NanoAdblocker/NanoDefender#30]
### URLs where this issue occurs (Required)
`http://ouo.io/7qfFYV`
`http://ouo.press/7qfFYV`

### Describe the issue (Optional if obvious)
Any ouo.io & ouo.press links are not solved, it goes on an endless loop..

Disabling Nano Defender opens the links normally..

#### Environment (Required)

- Browser and Version: Google Chrome 63
- Nano Adblocker Version: 1.0.0.34
- Nano Defender Version: 13.44

**Comment by jspenguin2017** [comment]
They fixed their Captcha...
