### ISSUE TITLE
bc.vc

### ISSUE THREAD

**Issue by gabri25ele** [NanoAdblocker/NanoDefender#31]
after ouo, also the http://bc.vc/ has problems to bypass.

**Comment by jspenguin2017** [comment]
Hum, if I create a new link, it tells me the link no longer exist. Do you have a test link?

**Comment by gabri25ele** [comment]
sorry, probably a one-link problem.
I did not have any problems after that.

**Comment by jspenguin2017** [comment]
Alright, closing then.
