### ISSUE TITLE
I think I could help you for the Firefox version ...

### ISSUE THREAD

**Issue by vrackfall** [NanoAdblocker/NanoDefender#33]
Hey Hugo Xu, if you want any help to finish NanoDefender for Firefox I think I can help you since I'm a Java / Web coder. I just need some help to setup my workspace (since I never did it before for Firefox addons).

**Comment by jspenguin2017** [comment]
Nano Defender is not written in Java.

**Comment by vrackfall** [comment]
I said also in a Web coder (PHP, HTML, Javascript). Also you know, I don't think it will be too complicated to port your extension from Chrome to Firefox, since it's pratically the same code, except for the interface.

**Comment by jspenguin2017** [comment]
OK, what do you need to know? 

The current build tools are in Nano Core, but that might change in the near future: 
```Bash
# Install dependencies
curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
sudo apt-get install -y nodejs
# Clone repos
git clone --depth 1 https://github.com/jspenguin2017/uBlockProtector
git clone --depth 1 https://github.com/NanoAdblocker/NanoCore.git
# Build
mkdir ./NanoCore/dist/build
cd ./NanoCore/scripts
node build-defender.node.js --firefox --use-ubr-repository
```

**Comment by vrackfall** [comment]
Ok thanks, I'll see if I'll be able to do something during this weekend.

**Comment by vrackfall** [comment]
Sorry I didn't get the time for now, starting tomorrow
