### ISSUE TITLE
techradar.com

### ISSUE THREAD

**Issue by pdbits** [NanoAdblocker/NanoDefender#35]
### URLs where this issue occurs (Required)
Any link on the techradar site:- https://www.techradar.com

### Screenshots (Required) 
Auto-redirect to **https://www.techradar.com/cc.html** for every link(with adblock and defender activated)

### Screenshot of console (Required, press `F12` to open the console)

![9bf33a54-aa5a-4465-9531-ef82f5d27211](https://user-images.githubusercontent.com/2222607/38169540-0ca4d6ac-355c-11e8-837b-695aba039def.jpg)

(On the auto-redirected page)

### Describe the issue (Optional if obvious)
Auto-redirect to https://www.techradar.com/cc.html for every link

### Reproduction Steps (Optional if trivial)
Just visit any article with uBO and NanoDefender activated, it triggers auto-redirect

### Anything else you believe to be useful (Optional):
[IMP] Yes, I believe it's due to the inclusion of techradar.com domain under the false positives parameter in the generic whitelist 1.

#### Environment (Required)

- Operating System and Version: Win8.1 64-bit
- Browser and Version: Chrome/64.0.3282.189
- uBO: 1.15.18
- Nano Defender Version: 13.49

#### Your filter lists (Required)
All uBO default

#### Your custom filters (Required if you have any)

Nano Defender Integration list
Nano Base Filters list

**Comment by jspenguin2017** [comment]
Can't reproduce. 
![image](https://user-images.githubusercontent.com/7283682/38174090-2c94b13e-3585-11e8-8e98-70118d53fa87.png)

> Yes, I believe it's due to the inclusion of techradar.com domain under the false positives parameter in the generic whitelist 1

Did you test this or it's just a speculation?

**Comment by pdbits** [comment]
Can you also try visiting any article link as well? Thank you.
As soon as I disable the adblock(uBO)(with defender activated), the issue goes away.
It's also reproduce on firefox.

> Did you test this or it's just a speculation?

Yeah, I am being instantly redirected to https://www.techradar.com/cc.html for every link I try to read. As shown by the console output on that page, it displays `[Nano] Excluded :: All Generically Applied Solutions`. As per my limited knowledge, this console message is only triggered when a certain domain is found on any of the whitelists(after viewing the message source in debugger). I could be wrong. 

Kindly check once more. Again, thank you for the amazing add-on and support.

**Comment by jspenguin2017** [comment]
Still can't reproduce. 
![image](https://user-images.githubusercontent.com/7283682/38176359-9b1105ca-35aa-11e8-9bf9-0f6b98e3c3c4.png)

**Comment by xlollomanx** [comment]
@pdbits me too cannot reproduce it. Make sure your filter is updated and proper filter enabled.

**Comment by pdbits** [comment]
@xlollomanx I already have; different setups(browsers) across diff OS(windows and ubuntu). With uBO 1.15.18 & above(with updated filters) and defender 13.49, whenever I visit a techradar link, I'm instantly being redirected to https://www.techradar.com/cc.html, with a certain console message(attached above). I do realize that you're not able to reproduce it, but I am unable to add any new info at this time, other than what I have already provided.
