### ISSUE TITLE
lequipe.fr

### ISSUE THREAD

**Issue by Francois-dag** [NanoAdblocker/NanoDefender#36]
got a popup "You are using an adblocker" ...
fixed by denying cookies from this site
last chrome and firefox using both 13.49.

Cheers.

**Comment by jspenguin2017** [comment]
@okiehsch I don't know if you would consider this annoyance on your side

**Comment by okiehsch** [comment]
I can't reproduce.
I would add such a filter, i.e. extended syntax dealing with an annoyance.

**Comment by mapx-** [comment]
probably already fixed ?
https://github.com/uBlockOrigin/uAssets/commit/c7853103486512995a3d432425f71ac906c6bee9

**Comment by okiehsch** [comment]
Well, that explains why I could not reproduce, sorry about that.
