### ISSUE TITLE
lejdd.fr

### ISSUE THREAD

**Issue by Francois-dag** [NanoAdblocker/NanoDefender#38]
https://www.lejdd.fr/sport/football/yuri-berchiche-defenseur-du-psg-en-france-les-adversaires-ne-sont-pas-assez-forts-3627080

La publicité soutient le journalisme et le contenu que vous lisez.
Il semblerait que vous utilisiez un Ad Blocker. Merci de choisir une option ......

#### Environment (Required)

- Operating System and Version: Windows 10
- Browser and Version: Firefox 59.0.2
- Nano Adblocker Version: 
- Nano Defender Version: 13.58

cheers !

**Comment by jspenguin2017** [comment]
@okiehsch
It's a hard anti-adblock, the article is cut. 
![image](https://user-images.githubusercontent.com/7283682/38780299-9a8bb1e4-4091-11e8-9754-80efb4284ff8.png)

**Comment by okiehsch** [comment]
I get the same wall even if I disable uBO, and have the choice to pay for the article or watch a video if I want to read the remaining 90% of the article.

![unbenannt](https://user-images.githubusercontent.com/16838044/38783696-fc11b7be-4105-11e8-8e43-816f0029456a.JPG)

**Comment by jspenguin2017** [comment]
It's an ads wall, *not paywall*, if it can be removed, it should be removed.

**Comment by okiehsch** [comment]
I agree that a badly implemented paywall shoul be removed, but I would put such a filter in `uBO-annoyances`.

**Comment by okiehsch** [comment]
Fixed in `uBO-filters`.

**Comment by jspenguin2017** [comment]
The fix for `webnovel.com` is in the main list, but this one lands in annoyance?

**Comment by okiehsch** [comment]
??? I said **Fixed in uBO-filters.**

**Comment by jspenguin2017** [comment]
Oh NVM I read it wrong.
