### ISSUE TITLE
discuss.freetutorials.us

### ISSUE THREAD

**Issue by paveltrufi** [NanoAdblocker/NanoDefender#42]
### URLs where this issue occurs (Required)
[https://discuss.freetutorials.us/](https://discuss.freetutorials.us/)

### Screenshots (Required)
![image](https://user-images.githubusercontent.com/9091619/39992182-3dae2bda-5772-11e8-99ef-0ad687d7fc88.png)

### Screenshot of console (Required, press `F12` to open the console)
![image](https://user-images.githubusercontent.com/9091619/39992195-4b3cbeb0-5772-11e8-9c2a-eb9885df0639.png)

### Describe the issue (Optional if obvious)
The red screen popUps after some seconds. The site is using [https://blockadblock.com/](https://blockadblock.com/)

#### Environment (Required)

- Operating System and Version: Linux Mint 18.3 Sylvia
- Browser and Version: Chrome 66.0.3359.170
- Nano Adblocker Version: 1.0.0.48
- Nano Defender Version: 14.23

#### Your filter lists (Required)
The default ones

#### Your custom filters (Required if you have any)
None

**Comment by krystian3w** [comment]
```
@@||discuss.freetutorials.us^$generichide
@@||freetutorials.us^$generichide
```

No hard BlockadBlock implementation now (I no must use `bab-defuser.js` or other exeption for FTU discourse forum)?

Chromimum self-signed version NanoDefender in Firefox kill BlockadBlock (maybe affected with no turn off dev mode).


![image](https://user-images.githubusercontent.com/35370833/40016770-bb4977c6-57b7-11e8-869e-42278199bde6.png) |
--- |

**Comment by okiehsch** [comment]
Fixed.

**Comment by paveltrufi** [comment]
Thank you, guys! :smile:
